"""Added subtitle to posts

Revision ID: d4f2d48f4a35
Revises: 
Create Date: 2022-08-01 17:28:52.561702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f2d48f4a35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('sub_title', sa.String(length=100), server_default='Social', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'sub_title')
    # ### end Alembic commands ###
